# Generated by Django 3.2 on 2025-02-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
